import { User } from './../models/user';
var users: User[] = [
    {
        "login": "lgruelas",
        "id": 10459639,
        "node_id": "MDQ6VXNlcjEwNDU5NjM5",
        "avatar_url": "https://avatars0.githubusercontent.com/u/10459639?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lgruelas",
        "html_url": "https://github.com/lgruelas",
        "followers_url": "https://api.github.com/users/lgruelas/followers",
        "following_url": "https://api.github.com/users/lgruelas/following{/other_user}",
        "gists_url": "https://api.github.com/users/lgruelas/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lgruelas/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lgruelas/subscriptions",
        "organizations_url": "https://api.github.com/users/lgruelas/orgs",
        "repos_url": "https://api.github.com/users/lgruelas/repos",
        "events_url": "https://api.github.com/users/lgruelas/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lgruelas/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Germán Ruelas",
        "company": null,
        "blog": "",
        "location": "México",
        "email": null,
        "hireable": true,
        "bio": "Mexican data science student",
        "public_repos": 7,
        "public_gists": 0,
        "followers": 2,
        "following": 1,
        "created_at": "2015-01-09T05:49:38Z",
        "updated_at": "2018-08-03T14:38:01Z"
    },
    {
        "login": "misael93",
        "id": 41706925,
        "node_id": "MDQ6VXNlcjQxNzA2OTI1",
        "avatar_url": "https://avatars1.githubusercontent.com/u/41706925?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/misael93",
        "html_url": "https://github.com/misael93",
        "followers_url": "https://api.github.com/users/misael93/followers",
        "following_url": "https://api.github.com/users/misael93/following{/other_user}",
        "gists_url": "https://api.github.com/users/misael93/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/misael93/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/misael93/subscriptions",
        "organizations_url": "https://api.github.com/users/misael93/orgs",
        "repos_url": "https://api.github.com/users/misael93/repos",
        "events_url": "https://api.github.com/users/misael93/events{/privacy}",
        "received_events_url": "https://api.github.com/users/misael93/received_events",
        "type": "User",
        "site_admin": false,
        "name": null,
        "company": null,
        "blog": "",
        "location": null,
        "email": null,
        "hireable": null,
        "bio": null,
        "public_repos": 4,
        "public_gists": 0,
        "followers": 0,
        "following": 0,
        "created_at": "2018-07-25T21:35:29Z",
        "updated_at": "2018-07-25T21:35:29Z"
    },
    {
        "login": "adjaf",
        "id": 26052310,
        "node_id": "MDQ6VXNlcjI2MDUyMzEw",
        "avatar_url": "https://avatars2.githubusercontent.com/u/26052310?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/adjaf",
        "html_url": "https://github.com/adjaf",
        "followers_url": "https://api.github.com/users/adjaf/followers",
        "following_url": "https://api.github.com/users/adjaf/following{/other_user}",
        "gists_url": "https://api.github.com/users/adjaf/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/adjaf/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/adjaf/subscriptions",
        "organizations_url": "https://api.github.com/users/adjaf/orgs",
        "repos_url": "https://api.github.com/users/adjaf/repos",
        "events_url": "https://api.github.com/users/adjaf/events{/privacy}",
        "received_events_url": "https://api.github.com/users/adjaf/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Antonio Avila Fernandez",
        "company": "Scio",
        "blog": "",
        "location": "Mexico",
        "email": null,
        "hireable": null,
        "bio": null,
        "public_repos": 7,
        "public_gists": 0,
        "followers": 0,
        "following": 0,
        "created_at": "2017-02-27T03:56:32Z",
        "updated_at": "2018-07-27T22:57:52Z"
    }
];

export const USERS_LIST = users;